#!/bin/bash

disable_apps="comments files_sharing files_versions"
mount_loc="/media/external"

# Install and configure nextcloud
pushd /var/www/owncloud
sudo -u www-data php occ maintenance:install --data-dir $mount_loc --database 'sqlite' --database-name 'owncloud' --admin-user 'mike' --admin-pass 'password'
for app in $disable_apps_; do sudo -u www-data php occ app:disable $app; done
popd
